services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: sandbox
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    ports:
      - '5432:5432'
